spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cpt?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.bjtu.examsys.domain
  mapper-locations: classpath:mapper/*.xml
